# Generated by Django 4.2.16 on 2024-11-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculation", "0005_delete_calculationprotocol"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="protection_device",
        ),
        migrations.RemoveField(
            model_name="protectiondevice",
            name="components",
        ),
        migrations.DeleteModel(
            name="Component",
        ),
        migrations.DeleteModel(
            name="Line",
        ),
        migrations.DeleteModel(
            name="ProtectionDevice",
        ),
    ]
