# Generated by Django 4.2.16 on 2024-11-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculationProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component", models.CharField(max_length=100, verbose_name="Орган")),
                (
                    "condition",
                    models.CharField(max_length=100, verbose_name="Расчетное условие"),
                ),
                ("result_value", models.FloatField(verbose_name="Значение уставки")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.line"
                    ),
                ),
            ],
            options={
                "verbose_name": "Протокол расчета",
                "verbose_name_plural": "Протоколы расчетов",
            },
        ),
    ]
