# Generated by Django 4.2.16 on 2024-11-21 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculationprotocol",
            name="condition",
        ),
    ]
