# Generated by Django 4.2.16 on 2024-11-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculation", "0002_remove_calculationprotocol_condition"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CalculationProtocol",
        ),
    ]
