# Generated by Django 4.2.16 on 2024-11-21 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("calculation", "0003_delete_calculationprotocol"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculationProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_value", models.FloatField(verbose_name="Значение уставки")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.component"
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.line"
                    ),
                ),
            ],
            options={
                "verbose_name": "Протокол расчета",
                "verbose_name_plural": "Протоколы расчетов",
            },
        ),
    ]
