# Generated by Django 4.2.16 on 2024-11-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculation", "0004_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CalculationProtocol",
        ),
    ]
